services:
  back:
    build:
      context: back
      target: final
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
      - POSTGRES_DB=blog
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U blog
      interval: 5s
      timeout: 2s
      retries: 15
volumes:
  db-data:
