services:
  back:
    build:
      context: back
    ports:
      - "8000:8000"
    volumes:
      - ./back/src:/app/src
    environment:
      - DATABASE_URL=postgres://blog:blog@db/blog
    depends_on:
      db:
        condition: service_healthy
  front:
    build:
      context: front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U blog
      interval: 5s
      timeout: 2s
      retries: 15
volumes:
  db-data:
