name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    container: node:20
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: corepack enable && cd front && pnpm install

      - name: Build
        run: cd front && pnpm build

      - name: Copy files
        run: |
          echo "${{ secrets.REMOTE_SSH_KEY }}" > key && \
          chmod 600 key && \
          cd front && \
          mv build front && \
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../key -P ${{ secrets.REMOTE_SSH_PORT }} -r front ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }}:/var/www/ivan.konorkin.com
