name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    container: node:20
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: corepack enable && cd front && pnpm install

      - name: Build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: cd front && pnpm build

      - name: Copy files
        run: |
          echo "${{ secrets.REMOTE_SSH_KEY }}" > key && \
          chmod 600 key && \
          cd front && \
          mv build front && \
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../key -P ${{ secrets.REMOTE_SSH_PORT }} -r front ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }}:/var/www/ivan.konorkin.com

  deploy-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /var/www/ivan.konorkin.com/blog && \
            git checkout main && \
            git pull

      - name: Build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /var/www/ivan.konorkin.com/blog/back && \
            cargo build --release && \
            mv --force target/release/back /var/www/ivan.konorkin.com/back/new_back

      - name: Restart server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /var/www/ivan.konorkin.com/back && \
            killall back || true && \
            rm -f back && \
            mv new_back back && \
            nohup ./back > nohup.out 2> nohup.err < /dev/null &

